<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
?>
<div class="container" id="iem-footer">
<hr />

 <div class="pull-right">
 <form method="get" action="https://www.google.com/search" name="search" 
 class="inline-form">
 <input value="id3b.agron.iastate.edu" name="sitesearch" type="hidden" />
 
 <div class="form-group">
    <label for="inputsearch">Search Site with Google</label>
    <input type="text" class="form-control" name="q" id="inputsearch" placeholder="Enter search term">
  </div>
 </form>
 </div>

 <i class="glyphicon glyphicon-earphone"></i> <a href="/contacts.php">contact us</a>
 <i class="glyphicon glyphicon-wrench"></i> <a href="https://github.com/akrherz/id3b">development</a>
 <i class="glyphicon glyphicon-warning-sign"></i> <a href="/disclaimer.php">disclaimer</a>
 
</div><!-- /.iem-footer -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="/vendor/jquery-ui/1.11.4/jquery-ui.min.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>
